### ISSUE TITLE
PhantomJS not found

### ISSUE THREAD

**Issue by GCinellu** [gruntjs/grunt-lib-phantomjs#100]
Hello everyone,

I am trying to run a snapshot of my application with PhantomJS, but this is what happens:

    Running PhantomJS...ERROR
    >> In order for this task to work properly, PhantomJS must be installed locally
    >> via NPM. If you're seeing this message, generally that means the NPM install
    >> has failed. Please submit an issue providing as much detail as possible at:
    >> https://github.com/gruntjs/grunt-lib-phantomjs/issues
    Warning: PhantomJS not found. Use --force to continue.

    Aborted due to warnings.

However I am 100% phantom is installed, indeed:

    user@ubuntu$ which phantomjs
    /usr/local/bin/phantomjs

What could cause and eventually solve this issue?

Thanks!

**Comment by Arkni** [comment]
Which version of this package are you using ?
Can you do some debugging and check if the [`binPath`](https://github.com/gruntjs/grunt-lib-phantomjs/blob/master/lib/phantomjs.js#L22) has a value ?

**Comment by GCinellu** [comment]
I am using 2.1.3.

The binPath has no value set, however the procedure was working fine before we migrated to a new environment.

The following is the output of my npm install command:

`npm WARN package.json Republiq@0.1.0 No description
npm WARN package.json Republiq@0.1.0 No repository field.
npm WARN package.json Republiq@0.1.0 No license field.
npm WARN deprecated graceful-fs@1.1.14: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
|
> phantomjs@1.8.2-0 install /var/lib/jenkins/jobs/Deploy to production VAULT/workspace/client/node_modules/phantomjs
> node install.js

Requesting /var/lib/jenkins/jobs/Deploy to production VAULT/workspace/client/node_modules/phantomjs/tmp/phantomjs-1.8.2-linux-x86_64.tar.bz2
Receiving...
Received 798K...
Received 1582K...
Received 2366K...
Received 3166K...
Received 3966K...
Received 4764K...
Received 5564K...
Received 6364K...
Received 7164K...
Received 7964K...
Received 8762K...
Received 9563K...
Received 10362K...
Received 11145K...
Received 11930K...
Received 12714K...
Received 12933K total.
Extracting tar contents (via spawned process)
Renaming extracted folder phantomjs-1.8.2-linux-x86_64  -> phantom
Done. Phantomjs binary available at /var/lib/jenkins/jobs/Deploy to production VAULT/workspace/client/node_modules/phantomjs/lib/phantom/bin/phantomjs

> phantomjs-prebuilt@2.1.5 install /var/lib/jenkins/jobs/Deploy to production VAULT/workspace/client/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS is previously installed at phantom/bin/phantomjs

> Republiq@0.1.0 postinstall /var/lib/jenkins/jobs/Deploy to production VAULT/workspace/client
> node_modules/bower/bin/bower --force install

bower jasmine-matchers#*       resolve https://github.com/JamieMason/Jasmine-Matchers.git#*
bower angular#=1.4.8           resolve git://github.com/angular/bower-angular.git#=1.4.8
bower requirejs-domready#=2.0.1          resolve git://github.com/requirejs/domReady.git#=2.0.1
bower angular-ui-router#=0.2.15          resolve git://github.com/angular-ui/angular-ui-router-bower.git#=0.2.15
bower angular-ui-select2#=0.0.5          resolve git://github.com/angular-ui/ui-select2.git#=0.0.5
bower requirejs#=2.1.9                   resolve git://github.com/jrburke/requirejs-bower.git#=2.1.9
bower angular-scroll#=1.0.0              resolve git://github.com/oblador/angular-scroll.git#=1.0.0
bower jquery.transit#~0.9.9              resolve git://github.com/rstacruz/jquery.transit.git#~0.9.9
bower requirejs-text#=2.0.10             resolve git://github.com/requirejs/text.git#=2.0.10
bower angular-i18n#~1.4.8                resolve git://github.com/angular/bower-angular-i18n.git#~1.4.8
bower iban#=0.0.4                        resolve git://github.com/arhs/iban.js.git#=0.0.4
bower angular-ui-utils#=0.1.1            resolve git://github.com/angular-ui/ui-utils.git#=0.1.1
bower angular-mocks#=1.4.8               resolve git://github.com/angular/bower-angular-mocks.git#=1.4.8
bower angular-resource#=1.4.8            resolve git://github.com/angular/bower-angular-resource.git#=1.4.8
bower requestAnimationFrame#~0.0.20      resolve git://github.com/cagosta/requestAnimationFrame.git#~0.0.20
bower angular-animate#=1.4.8             resolve git://github.com/angular/bower-angular-animate.git#=1.4.8
bower select2#~3.4                       resolve git://github.com/ivaynberg/select2.git#~3.4
bower skrollr#=0.6.21                    resolve git://github.com/Prinzhorn/skrollr.git#=0.6.21
bower angular-sanitize#=1.4.8            resolve git://github.com/angular/bower-angular-sanitize.git#=1.4.8
bower jquery-ui#=1.10.3                  resolve git://github.com/components/jqueryui.git#=1.10.3
bower font-awesome#~4.4.0                resolve git://github.com/FortAwesome/Font-Awesome.git#~4.4.0
bower angular-xeditable#=0.1.9           resolve git://github.com/vitalets/angular-xeditable.git#=0.1.9
bower underscore#=1.5.2                  resolve git://github.com/jashkenas/underscore.git#=1.5.2
bower angular-ui-grid#=3.0.7             resolve git://github.com/angular-ui/bower-ui-grid.git#=3.0.7
bower angular-cookies#=1.4.8             resolve git://github.com/angular/bower-angular-cookies.git#=1.4.8
bower angular-ui-sortable#=0.13.4        resolve git://github.com/angular-ui/ui-sortable.git#=0.13.4
bower jquery#=1.9.1                      resolve git://github.com/jquery/jquery-dist.git#=1.9.1
bower fotorama#~4.5.0                    resolve git://github.com/artpolikarpov/fotorama-bower.git#~4.5.0
bower jquery-waitforimages#=1.5.0        resolve git://github.com/StarterSquad/waitForImages.git#=1.5.0
bower angular-ui-map#=0.5.0              resolve git://github.com/angular-ui/ui-map.git#=0.5.0
bower requirejs-plugins#=1.0.2           resolve git://github.com/millermedeiros/requirejs-plugins.git#=1.0.2
bower requirejs-domready#=2.0.1         download https://github.com/requirejs/domReady/archive/2.0.1.tar.gz
bower jasmine-matchers#*                checkout 2.0.2
bower angular-ui-router#=0.2.15         download https://github.com/angular-ui/angular-ui-router-bower/archive/0.2.15.tar.gz
bower angular-ui-select2#=0.0.5         download https://github.com/angular-ui/ui-select2/archive/v0.0.5.tar.gz
bower requirejs#=2.1.9                  download https://github.com/jrburke/requirejs-bower/archive/2.1.9.tar.gz
bower jquery.transit#~0.9.9             download https://github.com/rstacruz/jquery.transit/archive/v0.9.12.tar.gz
bower angular-scroll#=1.0.0             download https://github.com/oblador/angular-scroll/archive/v1.0.0.tar.gz
bower requirejs-text#=2.0.10            download https://github.com/requirejs/text/archive/2.0.10.tar.gz
bower angular#=1.4.8                    download https://github.com/angular/bower-angular/archive/v1.4.8.tar.gz
bower angular-ui-utils#=0.1.1           download https://github.com/angular-ui/ui-utils/archive/v0.1.1.tar.gz
bower iban#=0.0.4                       download https://github.com/arhs/iban.js/archive/v0.0.4.tar.gz
bower angular-resource#=1.4.8           download https://github.com/angular/bower-angular-resource/archive/v1.4.8.tar.gz
bower angular-mocks#=1.4.8              download https://github.com/angular/bower-angular-mocks/archive/v1.4.8.tar.gz
bower angular-i18n#~1.4.8               download https://github.com/angular/bower-angular-i18n/archive/v1.4.9.tar.gz
bower skrollr#=0.6.21                   download https://github.com/Prinzhorn/skrollr/archive/0.6.21.tar.gz
bower select2#~3.4                      download https://github.com/ivaynberg/select2/archive/3.4.8.tar.gz
bower requestAnimationFrame#~0.0.20     download https://github.com/cagosta/requestAnimationFrame/archive/v0.0.23.tar.gz
bower angular-sanitize#=1.4.8           download https://github.com/angular/bower-angular-sanitize/archive/v1.4.8.tar.gz
bower angular-animate#=1.4.8            download https://github.com/angular/bower-angular-animate/archive/v1.4.8.tar.gz
bower angular-ui-grid#=3.0.7            download https://github.com/angular-ui/bower-ui-grid/archive/v3.0.7.tar.gz
bower underscore#=1.5.2                 download https://github.com/jashkenas/underscore/archive/1.5.2.tar.gz
bower font-awesome#~4.4.0               download https://github.com/FortAwesome/Font-Awesome/archive/v4.4.0.tar.gz
bower angular-xeditable#=0.1.9          download https://github.com/vitalets/angular-xeditable/archive/0.1.9.tar.gz
bower jquery-ui#=1.10.3                 download https://github.com/components/jqueryui/archive/1.10.3.tar.gz
bower requirejs-domready#=2.0.1          extract archive.tar.gz
bower fotorama#~4.5.0                   download https://github.com/artpolikarpov/fotorama-bower/archive/4.5.2.tar.gz
bower jquery-waitforimages#=1.5.0       download https://github.com/StarterSquad/waitForImages/archive/1.5.0.tar.gz
bower requirejs-domready#=2.0.1     invalid-meta domReady is missing "ignore" entry in bower.json
bower angular-ui-sortable#=0.13.4       download https://github.com/angular-ui/ui-sortable/archive/v0.13.4.tar.gz
bower angular-ui-select2#=0.0.5          extract archive.tar.gz
bower requirejs-domready#=2.0.1         resolved git://github.com/requirejs/domReady.git#2.0.1
bower jquery#=1.9.1                     download https://github.com/jquery/jquery-dist/archive/1.9.1.tar.gz
bower angular-ui-select2#=0.0.5     invalid-meta angular-ui-select2 is missing "ignore" entry in bower.json
bower angular-ui-select2#=0.0.5         resolved git://github.com/angular-ui/ui-select2.git#0.0.5
bower angular-ui-map#=0.5.0             download https://github.com/angular-ui/ui-map/archive/v0.5.0.tar.gz
bower angular-ui-router#=0.2.15          extract archive.tar.gz
bower requirejs-plugins#=1.0.2          download https://github.com/millermedeiros/requirejs-plugins/archive/v1.0.2.tar.gz
bower requirejs-text#=2.0.10             extract archive.tar.gz
bower requirejs-text#=2.0.10        invalid-meta requirejs-text is missing "main" entry in bower.json
bower requirejs-text#=2.0.10        invalid-meta requirejs-text is missing "ignore" entry in bower.json
bower jquery.transit#~0.9.9              extract archive.tar.gz
bower requirejs-text#=2.0.10            resolved git://github.com/requirejs/text.git#2.0.10
bower angular-cookies#=1.4.8            download https://github.com/angular/bower-angular-cookies/archive/v1.4.8.tar.gz
bower angular-scroll#=1.0.0              extract archive.tar.gz
bower angular-ui-utils#=0.1.1            extract archive.tar.gz
bower requestAnimationFrame#~0.0.20      extract archive.tar.gz
bower jquery.transit#~0.9.9         invalid-meta jquery.transit is missing "ignore" entry in bower.json
bower iban#=0.0.4                        extract archive.tar.gz
bower jquery.transit#~0.9.9             resolved git://github.com/rstacruz/jquery.transit.git#0.9.12
bower angular-ui-utils#=0.1.1       invalid-meta angular-ui-utils is missing "ignore" entry in bower.json
bower angular-ui-utils#=0.1.1           resolved git://github.com/angular-ui/ui-utils.git#0.1.1
bower angular-resource#=1.4.8            extract archive.tar.gz
bower angular-mocks#=1.4.8               extract archive.tar.gz
bower requestAnimationFrame#~0.0.20 invalid-meta requestAnimationFrame is missing "ignore" entry in bower.json
bower requestAnimationFrame#~0.0.20     resolved git://github.com/cagosta/requestAnimationFrame.git#0.0.23
bower iban#=0.0.4                   invalid-meta iban is missing "main" entry in bower.json
bower iban#=0.0.4                   invalid-meta iban is missing "ignore" entry in bower.json
bower angular-sanitize#=1.4.8            extract archive.tar.gz
bower iban#=0.0.4                       resolved git://github.com/arhs/iban.js.git#0.0.4
bower requirejs#=2.1.9                   extract archive.tar.gz
bower angular-resource#=1.4.8           resolved git://github.com/angular/bower-angular-resource.git#1.4.8
bower angular-ui-router#=0.2.15         resolved git://github.com/angular-ui/angular-ui-router-bower.git#0.2.15
bower angular-mocks#=1.4.8              resolved git://github.com/angular/bower-angular-mocks.git#1.4.8
bower requirejs#=2.1.9              invalid-meta requirejs is missing "main" entry in bower.json
bower requirejs#=2.1.9              invalid-meta requirejs is missing "ignore" entry in bower.json
bower requirejs#=2.1.9                  resolved git://github.com/jrburke/requirejs-bower.git#2.1.9
bower angular-sanitize#=1.4.8           resolved git://github.com/angular/bower-angular-sanitize.git#1.4.8
bower angular-animate#=1.4.8             extract archive.tar.gz
bower angular-i18n#~1.4.8                extract archive.tar.gz
bower angular-ui-sortable#=0.13.4        extract archive.tar.gz
bower fotorama#~4.5.0                    extract archive.tar.gz
bower angular-animate#=1.4.8            resolved git://github.com/angular/bower-angular-animate.git#1.4.8
bower angular-ui-utils#0.x               resolve git://github.com/angular-ui/ui-utils.git#0.x
bower angular-ui-sortable#=0.13.4   invalid-meta angular-ui-sortable is missing "ignore" entry in bower.json
bower angular-ui-utils#0.x              download https://github.com/angular-ui/ui-utils/archive/v0.2.3.tar.gz
bower angular-ui-sortable#=0.13.4       resolved git://github.com/angular-ui/ui-sortable.git#0.13.4
bower angular-scroll#=1.0.0             resolved git://github.com/oblador/angular-scroll.git#1.0.0
bower angular-ui-map#=0.5.0              extract archive.tar.gz
bower angular-ui-map#=0.5.0         invalid-meta angular-ui-map is missing "ignore" entry in bower.json
bower angular-ui-map#=0.5.0             resolved git://github.com/angular-ui/ui-map.git#0.5.0
bower fotorama#~4.5.0                   resolved git://github.com/artpolikarpov/fotorama-bower.git#4.5.2
bower select2#~3.4                       extract archive.tar.gz
bower angular#=1.4.8                     extract archive.tar.gz
bower angular-ui-grid#=3.0.7             extract archive.tar.gz
bower skrollr#=0.6.21                    extract archive.tar.gz
bower angular-cookies#=1.4.8             extract archive.tar.gz
bower jquery-waitforimages#=1.5.0        extract archive.tar.gz
bower underscore#=1.5.2                  extract archive.tar.gz
bower angular-cookies#=1.4.8            resolved git://github.com/angular/bower-angular-cookies.git#1.4.8
bower angular#=1.4.8                    resolved git://github.com/angular/bower-angular.git#1.4.8
bower jquery-waitforimages#=1.5.0   invalid-meta jquery-waitforimages is missing "main" entry in bower.json
bower jquery-waitforimages#=1.5.0   invalid-meta jquery-waitforimages is missing "ignore" entry in bower.json
bower jquery-waitforimages#=1.5.0       resolved git://github.com/StarterSquad/waitForImages.git#1.5.0
bower jquery#=1.9.1                      extract archive.tar.gz
bower select2#~3.4                  invalid-meta select2 is missing "ignore" entry in bower.json
bower select2#~3.4                      resolved git://github.com/ivaynberg/select2.git#3.4.8
bower skrollr#=0.6.21               invalid-meta skrollr is missing "main" entry in bower.json
bower skrollr#=0.6.21               invalid-meta skrollr is missing "ignore" entry in bower.json
bower skrollr#=0.6.21                   resolved git://github.com/Prinzhorn/skrollr.git#0.6.21
bower requirejs-plugins#=1.0.2           extract archive.tar.gz
bower angular#>=1.2.0                    resolve git://github.com/angular/bower-angular.git#>=1.2.0
bower angular#>=1.2.0                   download https://github.com/angular/bower-angular/archive/v1.5.0.tar.gz
bower angular#^1.2.16                    resolve git://github.com/angular/bower-angular.git#^1.2.16
bower angular#1.4.8                      resolve git://github.com/angular/bower-angular.git#1.4.8
bower angular#>=1.2.16 1.4.x             resolve git://github.com/angular/bower-angular.git#>=1.2.16 1.4.x
bower angular#~1.x                       resolve git://github.com/angular/bower-angular.git#~1.x
bower angular#>= 1.0.8                   resolve git://github.com/angular/bower-angular.git#>= 1.0.8
bower angular#1.x                        resolve git://github.com/angular/bower-angular.git#1.x
bower angular#>=1.2.x                    resolve git://github.com/angular/bower-angular.git#>=1.2.x
bower angular#>= 1.0.2                   resolve git://github.com/angular/bower-angular.git#>= 1.0.2
bower underscore#=1.5.2             invalid-meta underscore is missing "main" entry in bower.json
bower underscore#=1.5.2             invalid-meta underscore is missing "ignore" entry in bower.json
bower angular#^1.2.16                   download https://github.com/angular/bower-angular/archive/v1.5.0.tar.gz
bower angular#1.4.8                     download https://github.com/angular/bower-angular/archive/v1.4.8.tar.gz
bower angular#>=1.2.16 1.4.x            download https://github.com/angular/bower-angular/archive/v1.4.9.tar.gz
bower angular#~1.x                      download https://github.com/angular/bower-angular/archive/v1.5.0.tar.gz
bower angular#>= 1.0.8                  download https://github.com/angular/bower-angular/archive/v1.5.0.tar.gz
bower angular#1.x                       download https://github.com/angular/bower-angular/archive/v1.5.0.tar.gz
bower angular#>=1.2.x                   download https://github.com/angular/bower-angular/archive/v1.5.0.tar.gz
bower angular#>= 1.0.2                  download https://github.com/angular/bower-angular/archive/v1.5.0.tar.gz
bower angular-ui-grid#=3.0.7            resolved git://github.com/angular-ui/bower-ui-grid.git#3.0.7
bower underscore#=1.5.2                 resolved git://github.com/jashkenas/underscore.git#1.5.2
bower angular-ui-utils#0.x               extract archive.tar.gz
bower angular-ui-utils#0.x          invalid-meta angular-ui-utils is missing "ignore" entry in bower.json
bower angular-ui-utils#0.x              resolved git://github.com/angular-ui/ui-utils.git#0.2.3
bower requirejs-plugins#=1.0.2          resolved git://github.com/millermedeiros/requirejs-plugins.git#1.0.2
bower jquery-ui#=1.10.3                  extract archive.tar.gz
bower jquery#=1.9.1                   deprecated Package jquery is using the deprecated component.json
bower jquery#=1.9.1                 invalid-meta jquery is missing "main" entry in bower.json
bower jquery#=1.9.1                 invalid-meta jquery is missing "ignore" entry in bower.json
bower jquery#=1.9.1                     resolved git://github.com/jquery/jquery-dist.git#1.9.1
bower font-awesome#~4.4.0                extract archive.tar.gz
bower jquery#>=1.6                       resolve git://github.com/jquery/jquery-dist.git#>=1.6
bower jquery#>=1.6                      download https://github.com/jquery/jquery-dist/archive/2.2.1.tar.gz
bower jquery#>=1.6.4                     resolve git://github.com/jquery/jquery-dist.git#>=1.6.4
bower jquery#>= 1.7.1                    resolve git://github.com/jquery/jquery-dist.git#>= 1.7.1
bower jquery#>=1.8                       resolve git://github.com/jquery/jquery-dist.git#>=1.8
bower jquery#>=1.6.4                    download https://github.com/jquery/jquery-dist/archive/2.2.1.tar.gz
bower jquery#*                           resolve git://github.com/jquery/jquery-dist.git#*
bower jquery#>= 1.7.1                   download https://github.com/jquery/jquery-dist/archive/2.2.1.tar.gz
bower jquery#>=1.8                      download https://github.com/jquery/jquery-dist/archive/2.2.1.tar.gz
bower jquery#*                          download https://github.com/jquery/jquery-dist/archive/2.2.1.tar.gz
bower angular-xeditable#=0.1.9           extract archive.tar.gz
bower angular#>=1.2.0                    extract archive.tar.gz
bower angular#^1.2.16                    extract archive.tar.gz
bower angular#1.4.8                      extract archive.tar.gz
bower angular#>= 1.0.2                   extract archive.tar.gz
bower angular#>=1.2.x                    extract archive.tar.gz
bower angular#>= 1.0.8                   extract archive.tar.gz
bower angular#~1.x                       extract archive.tar.gz
bower angular#>=1.2.0                   resolved git://github.com/angular/bower-angular.git#1.5.0
bower angular#>=1.2.16 1.4.x             extract archive.tar.gz
bower angular#1.x                        extract archive.tar.gz
bower angular#^1.2.16                   resolved git://github.com/angular/bower-angular.git#1.5.0
bower angular#1.4.8                     resolved git://github.com/angular/bower-angular.git#1.4.8
bower angular#>=1.2.x                   resolved git://github.com/angular/bower-angular.git#1.5.0
bower angular#>= 1.0.2                  resolved git://github.com/angular/bower-angular.git#1.5.0
bower angular#>= 1.0.8                  resolved git://github.com/angular/bower-angular.git#1.5.0
bower angular#~1.x                      resolved git://github.com/angular/bower-angular.git#1.5.0
bower angular#>=1.2.16 1.4.x            resolved git://github.com/angular/bower-angular.git#1.4.9
bower angular#1.x                       resolved git://github.com/angular/bower-angular.git#1.5.0
bower jquery#>= 1.7.1                    extract archive.tar.gz
bower jquery#>=1.6                       extract archive.tar.gz
bower jquery#>=1.6.4                     extract archive.tar.gz
bower jquery#>=1.8                       extract archive.tar.gz
bower jquery#*                           extract archive.tar.gz
bower jasmine-matchers#*                mismatch Version declared in the json (2.0.0-beta1) is different than the resolved one (2.0.2)
bower jasmine-matchers#*                resolved https://github.com/JamieMason/Jasmine-Matchers.git#2.0.2
bower jquery#>= 1.7.1                   resolved git://github.com/jquery/jquery-dist.git#2.2.1
bower jquery#>=1.6                      resolved git://github.com/jquery/jquery-dist.git#2.2.1
bower jquery#>=1.6.4                    resolved git://github.com/jquery/jquery-dist.git#2.2.1
bower jquery#>=1.8                      resolved git://github.com/jquery/jquery-dist.git#2.2.1
bower jquery#*                          resolved git://github.com/jquery/jquery-dist.git#2.2.1
bower angular-xeditable#=0.1.9          resolved git://github.com/vitalets/angular-xeditable.git#0.1.9
bower jquery-ui#=1.10.3             invalid-meta jquery-ui is missing "ignore" entry in bower.json
bower jquery-ui#=1.10.3                 resolved git://github.com/components/jqueryui.git#1.10.3
bower jquery-ui#>=1.9                    resolve git://github.com/components/jqueryui.git#>=1.9
bower jquery-ui#>=1.9                   download https://github.com/components/jqueryui/archive/1.11.4.tar.gz
bower font-awesome#~4.4.0               resolved git://github.com/FortAwesome/Font-Awesome.git#4.4.0
bower jquery-ui#>=1.9                    extract archive.tar.gz
bower angular-i18n#~1.4.8           invalid-meta angular-i18n is missing "main" entry in bower.json
bower angular-i18n#~1.4.8               resolved git://github.com/angular/bower-angular-i18n.git#1.4.9
bower jquery-ui#>=1.9                   resolved git://github.com/components/jqueryui.git#1.11.4
bower requirejs-domready#=2.0.1          install requirejs-domready#2.0.1
bower angular-ui-select2#=0.0.5          install angular-ui-select2#0.0.5
bower requirejs-text#=2.0.10             install requirejs-text#2.0.10
bower jquery.transit#~0.9.9              install jquery.transit#0.9.12
bower angular-ui-utils#=0.1.1            install angular-ui-utils#0.1.1
bower requestAnimationFrame#~0.0.20      install requestAnimationFrame#0.0.23
bower iban#=0.0.4                        install iban#0.0.4
bower angular-resource#=1.4.8            install angular-resource#1.4.8
bower angular-ui-router#=0.2.15          install angular-ui-router#0.2.15
bower angular-mocks#=1.4.8               install angular-mocks#1.4.8
bower requirejs#=2.1.9                   install requirejs#2.1.9
bower angular-sanitize#=1.4.8            install angular-sanitize#1.4.8
bower angular-animate#=1.4.8             install angular-animate#1.4.8
bower angular-ui-sortable#=0.13.4        install angular-ui-sortable#0.13.4
bower angular-scroll#=1.0.0              install angular-scroll#1.0.0
bower angular-ui-map#=0.5.0              install angular-ui-map#0.5.0
bower fotorama#~4.5.0                    install fotorama#4.5.2
bower angular-cookies#=1.4.8             install angular-cookies#1.4.8
bower angular#=1.4.8                     install angular#1.4.8
bower jquery-waitforimages#=1.5.0        install jquery-waitforimages#1.5.0
bower select2#~3.4                       install select2#3.4.8
bower skrollr#=0.6.21                    install skrollr#0.6.21
bower angular-ui-grid#=3.0.7             install angular-ui-grid#3.0.7
bower underscore#=1.5.2                  install underscore#1.5.2
bower requirejs-plugins#=1.0.2           install requirejs-plugins#1.0.2
bower jquery#=1.9.1                      install jquery#1.9.1
bower jasmine-matchers#*                 install jasmine-matchers#2.0.2
bower angular-xeditable#=0.1.9           install angular-xeditable#0.1.9
bower jquery-ui#=1.10.3                  install jquery-ui#1.10.3
bower font-awesome#~4.4.0                install font-awesome#4.4.0
bower angular-i18n#~1.4.8                install angular-i18n#1.4.9

requirejs-domready#2.0.1 source/vendor/requirejs-domready

angular-ui-select2#0.0.5 source/vendor/angular-ui-select2
├── angular#1.4.8
├── jquery#1.9.1
└── select2#3.4.8

requirejs-text#2.0.10 source/vendor/requirejs-text

jquery.transit#0.9.12 source/vendor/jquery.transit
└── jquery#1.9.1

angular-ui-utils#0.1.1 source/vendor/angular-ui-utils
└── angular#1.4.8

requestAnimationFrame#0.0.23 source/vendor/requestAnimationFrame

iban#0.0.4 source/vendor/iban

angular-resource#1.4.8 source/vendor/angular-resource
└── angular#1.4.8

angular-ui-router#0.2.15 source/vendor/angular-ui-router
└── angular#1.4.8

angular-mocks#1.4.8 source/vendor/angular-mocks
└── angular#1.4.8

requirejs#2.1.9 source/vendor/requirejs

angular-sanitize#1.4.8 source/vendor/angular-sanitize
└── angular#1.4.8

angular-animate#1.4.8 source/vendor/angular-animate
└── angular#1.4.8

angular-ui-sortable#0.13.4 source/vendor/angular-ui-sortable
├── angular#1.4.8
└── jquery-ui#1.10.3

angular-scroll#1.0.0 source/vendor/angular-scroll
└── angular#1.4.8

angular-ui-map#0.5.0 source/vendor/angular-ui-map
├── angular#1.4.8
└── angular-ui-utils#0.1.1

fotorama#4.5.2 source/vendor/fotorama
└── jquery#1.9.1

angular-cookies#1.4.8 source/vendor/angular-cookies
└── angular#1.4.8

angular#1.4.8 source/vendor/angular

jquery-waitforimages#1.5.0 source/vendor/jquery-waitforimages

select2#3.4.8 source/vendor/select2
└── jquery#1.9.1

skrollr#0.6.21 source/vendor/skrollr

angular-ui-grid#3.0.7 source/vendor/angular-ui-grid
└── angular#1.4.8

underscore#1.5.2 source/vendor/underscore

requirejs-plugins#1.0.2 source/vendor/requirejs-plugins

jquery#1.9.1 source/vendor/jquery

jasmine-matchers#2.0.2 source/vendor/jasmine-matchers

angular-xeditable#0.1.9 source/vendor/angular-xeditable
└── angular#1.4.8

jquery-ui#1.10.3 source/vendor/jquery-ui
└── jquery#1.9.1

font-awesome#4.4.0 source/vendor/font-awesome

angular-i18n#1.4.9 source/vendor/angular-i18n
npm WARN engineStrict Per-package engineStrict (found in this package's package.json) 
npm WARN engineStrict won't be used in npm 3+. Use the config setting `engine-strict` instead.
phantomjs@1.8.2-0 node_modules/phantomjs
├── rimraf@2.0.3 (graceful-fs@1.1.14)
└── unzip@0.1.11 (setimmediate@1.0.4, pullstream@0.4.1, match-stream@0.0.2, readable-stream@1.0.33, fstream@0.1.31, binary@0.3.0)`

**Comment by Arkni** [comment]
> The binPath has no value set, however the procedure was working fine before we migrated to a new environment.

If the `binPath` is empty, that means one thing: [`phantomjs`](https://github.com/Medium/phantomjs) package (aka `phantomjs-prebuilt`) can't find the binary even though it's installed correctly. That looks to me like a bug with [`phantomjs`](https://github.com/Medium/phantomjs) package, not this lib.

We can do anything about that, you have to report that to their [issue tracker](https://github.com/Medium/phantomjs/issues).

Just a side note, in the log you provided I see two different versions of `phantomjs` (`phantomjs@1.8.2-0` and `phantomjs-prebuilt@2.1.5`), you only have to use one (the latest).

**Comment by Arkni** [comment]
I'm going to close this, but feel free to ask if you have followup questions.
