### ISSUE TITLE
Remove or update dependency temporary@0.0.8

### ISSUE THREAD

**Issue by varunsikka** [gruntjs/grunt-lib-phantomjs#111]
The dependency temporary@0.0.8 is using peer dependency named package@1.0.1 and this dependency does not exist anymore in npm/yarn repos.
A pull request has been created by someone in temporary@0.0.8 and hopefully will be addressed soon. (https://github.com/vesln/temporary/pull/25)
Creating this issue to update the "temporary" version to the latest once the pull request is merged.

**Comment by Arkni** [comment]
Hi @varunsikka 

Thanks for the heads up.

The issue has been fixed by `npm` according to their incident report https://status.npmjs.org/incidents/36j9bnllqtnj, so no change is needed.

Thanks again.
