### ISSUE TITLE
Task not marked as failure if phantomjs fails unexpectedly

### ISSUE THREAD

**Issue by Krinkle** [gruntjs/grunt-lib-phantomjs#13]
From http://swarm.jquery.org:8080/job/QUnit/269/console:
![screenshot](https://f.cloud.github.com/assets/156867/239354/31da7a7e-8884-11e2-836d-d30cb805887d.png)

```
Running "qunit:addons" (qunit) task
Testing addons/canvas/canvas.html.OK
Testing addons/close-enough/close-enough.html
Running PhantomJS...ERROR
>> PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://code.google.com/p/phantomjs/issues/entry with the crash dump file attached: /tmp/1f83c906-7d4c-5760-418ee798-2dfc280c.dmp
Warning: PhantomJS exited unexpectedly with exit code null. Use --force to continue.

Aborted due to warnings.

Finished: SUCCESS
```

So the adventure begins
### Gruntfile ([jquery/qunit@2f7cad5204:/Gruntfile.js](https://github.com/jquery/qunit/blob/2f7cad5204265725cab67b562d18ee34029ad161/Gruntfile.js))

``` js
grunt.loadNpmTasks( "grunt-contrib-qunit" );
grunt.initConfig({
    qunit: {
        qunit: [
            "test/index.html",
            "test/async.html"
        ],
        addons: [
            "addons/canvas/canvas.html",
            "addons/close-enough/close-enough.html",
            "addons/composite/composite.html"
        ]
...
```
### Task ([gruntjs/grunt-contrib-qunit@master:/tasks/qunit.js](https://github.com/gruntjs/grunt-contrib-qunit/blob/d504b040c592a45dbee9fb9886414d14e391e750/tasks/qunit.js#L151))

``` js
    grunt.util.async.forEachSeries(urls, function(url, next) {
      grunt.verbose.subhead('Testing ' + url).or.write('Testing ' + url);

      grunt.event.emit('qunit.spawn', url);
      phantomjs.spawn(url, {
        options: options,
        done: function(err) {
          if (err) {
            done();
```
### Lib ([gruntjs/grunt-lib-phantomjs@master:/lib/phantomjs.js](https://github.com/gruntjs/grunt-lib-phantomjs/blob/3236655fce36d395b865780ec1fec2a3eec66627/lib/phantomjs.js#L37))

``` js
  exports.spawn = function(pageUrl, options) {
    var failCode = options.failCode || 0;

    return grunt.util.spawn({
      cmd: binPath,
      args: args
    }, function(err, result, code) {
      if (!err) { return; }

      grunt.log.write('Running PhantomJS...').error();
      if (code === 127) {
        ...
      } else {
        String(result).split('\n').forEach(grunt.log.error, grunt.log);
        grunt.warn('PhantomJS exited unexpectedly with exit code ' + code + '.', failCode);
      }
      options.done(code);
```
### Util ([gruntjs/grunt@master:/lib/grunt/util.js](https://github.com/gruntjs/grunt/blob/bfefd1129cb5a6a9de590ec95bb955a77fbb345f/lib/grunt/util.js#L121))

``` js
util.spawn = function(opts, done) {
  var callDone = function(code, stdout, stderr) {
    ...
    done(new Error(stderr), result, code);
  };

    try {
     ...
    } catch (err) {
      callDone(127, '', String(err));
      return;
    }

  var child = spawn(cmd, args, opts.opts);

  child.on('close', function(code) {
    callDone(code, stdout, stderr);
  });
```
### Child ([nodejs@0.8.2:/child](http://nodejs.org/docs/v0.8.2/api/child_process.html#child_process_event_exit))

> This event is emitted after the child process ends. If the process terminated
> normally, <code>code</code> is the final exit code of the process, otherwise <code>null</code>.

---

The problem is that the library is assuming that if there is an error the exit code is always truthy. However in case of an unexpected termination, node reports null. And even though the library does output the error to grunt, it outputs it with "warning" only. The exit code is determined by the `done()` handler which is given null, so it assumes there was no error.

In the error case, the library must call `options.done` with a truthy value. Changing it to `options.done( code || true );` or `options.done( code || 'Unexpected termination' );` should fix it.

**Comment by Arkni** [comment]
Your solution will work only if `force` flag or `--force` command-line option was specified.
So, in addition to what to you suggest, we have to pass a non zero `failCode` to `grunt.warn(...)`, that way we can make sure that the task will fail or `Grunt` should be aborted immediately with a non zero error code.

**Comment by Krinkle** [comment]
I've since then switched to using Chromium with Xvfb and Karma launcher.

**Comment by Arkni** [comment]
> I've since then switched to using Chromium with Xvfb and Karma launcher.

Nice collection. Noted :)
