### ISSUE TITLE
Running PhantomJS Error in yeoman's web app generator

### ISSUE THREAD

**Issue by chaoren1641** [gruntjs/grunt-lib-phantomjs#22]
I installed the the yeoman tools, and then run the following command

```
yo webapp
```

all the way to completion, and then run

```
grunt test
```

The terminal report an error
![image](https://f.cloud.github.com/assets/404245/401648/83671e22-a8e3-11e2-9723-e1d0feae92d5.png)

These operations are performed by default!Is this why?How to solve it?

my grunt version is 4.0 and yeoman version is 1.0.0-beta.3

thanks!

**Comment by fungjj92** [comment]
+1 life saving

**Comment by hypo-thesis** [comment]
`npm install phantomjs-prebuilt--ignore-scripts`

 saved me!
