### ISSUE TITLE
Add ability to specified explicit path to phantomjs.exe

### ISSUE THREAD

**Issue by evil-shrike** [gruntjs/grunt-lib-phantomjs#35]
This plugin uses npm module 'phantomjs' (https://github.com/Obvious/phantomjs) for installing phantomjs executable. Unfortunately there's an issue with 'phantomjs' module - it hard-codes absolute path to phantomjs.exe on installation (see Obvious/phantomjs#97). So sharing and commiting into VCSs node_modules folder is impossible. That's bad.
As a warkaroung I'd suggest to allow to specify explicit path to phantomjs.exe via an option to avoid using 'phantomjs' module at all.

**Comment by Arkni** [comment]
The package `phantomjs` (aka `phanotmjs-prebuilt`) has the ability to use the global installed `PhantomJS` if exist and fall back to locally installed binary.

Also the issue you linked to has been fixed long ago.

Closing this for now, feel free to ask if you have followup questions.
