### ISSUE TITLE
When exactly is "done" callback called in phantomjs.spawn method?

### ISSUE THREAD

**Issue by szimek** [gruntjs/grunt-lib-phantomjs#38]
I'm working on generating static HTML pages with PhantomJS for Google bot in our AngularJS app that uses HTML5 mode routing. I need it to wait until all templates are rendered by AngularJS and all Ajax requests are finished.

When using `phantomjs.spawn` method when exactly will "done" callback be called? Will it wait e.g. for Ajax calls to finish?

**Comment by Arkni** [comment]
This issue is really old, and I feel that you're talking about [`PhantomJS`](https://github.com/ariya/phantomjs) not this package.
Closing for now , feel free to ask if you have followup questions.
