### ISSUE TITLE
Local Npm module "grunt-lib-phantomjs" not found.

### ISSUE THREAD

**Issue by mwq27** [gruntjs/grunt-lib-phantomjs#48]
Local Npm module "grunt-lib-phantomjs" not found. Is it installed?

I am receiving the above error with the following package versions:

grunt 0.4.2
grunt-lib-phantomjs 0.4.0
grunt-lib-phantomjs/node_modules/phantomjs 1.9.0-1

I've seen this issue come up in older versions of phantom, but everyone says it should be fixed now.  Anyone else still seeing this bug?

**Comment by Siddharth77** [comment]
I hope it helps : 
Please run <npm install --unsafe-perm>
