### ISSUE TITLE
First install fail

### ISSUE THREAD

**Issue by jscti** [gruntjs/grunt-lib-phantomjs#61]
Hello

I must be missing something but can't find the problem so far :
I'm stuck with a timeout problem on a fresh install.

- Windows 7 64bits
- Node 0.10.26 / Npm 1.4.6
- Grunt 0.4.4
- npm install worked well
- grunt-lib-phantomjs 0.6.0
- I tried with and without adding bin folder (where phantomjs.exe is) in my PATH
- tried to extend timeout

Gruntfile.js code :
>// Spawn phantomjs
phantomjs.spawn(url, {
  // Additional PhantomJS options.
  options: {
    timeout: 15000
  },
  // Complete the task when done.
  done: function(err) {
    var body = document.getElementsByTagName('body')[0]; //generates an error "document is not defined"
    done(err);
  }
});

The problem :
while calling a working URL (local one or public one), phantom fails with a :
> grunt check-deployment
Running "check-deployment" task
Warning: PhantomJS timed out. Use --force to continue.

If using force/verbose/debug, I see that my HTML assets are loaded, but still getting the timeout issue. And I also see that, the phamtomJs code get called but fails (document is not defined) : 

>Running "check-deployment" task
[D] Task source: D:\Utilisateurs\xble769\_Data\workspace\MaPoste\v1\front\Gruntfile.js
PhantomJs loading http://domain.com ...
[D] ["D:\\Utilisateurs\\iuii\\_Data\\workspace\\MaPoste\\v1\\front\\node_modules\\grunt-lib-phantomjs\\phantomjs\\main.js","D:\\UTILIS~1\\iuii\\AppData\\Local\\Temp/1400572576431.9705","http://domain.com","{\"timeout\":15000}"]
[D] ["phantomjs","private","version",{"major":1,"minor":9,"patch":7}]
[D] ["phantomjs","onUrlChanged","http://domain.com/"]
[...]
[D] ["phantomjs","onLoadFinished","success"]
[D] ["phantomjs","fail.timeout"]
Warning: PhantomJS timed out. Used --force, continuing.
err [ReferenceError: document is not defined]Fatal error: Cannot read property 'appVersion' of undefined

Any clue ?

**Comment by Arkni** [comment]
This issue dates 2 years. Are you still getting this error ? Did you solve your problem ?

From the stack trace, I see that the mean problem is something related to `appVersion` property which is not used in any file in this package.

Closing this for now, feel free to ask if you have followup questions.
