### ISSUE TITLE
Local Npm module "grunt-lib-phantomjs" not found. Is it installed? [windows]

### ISSUE THREAD

**Issue by punkbit** [gruntjs/grunt-lib-phantomjs#66]
Issue:

```
Running PhantomJS...ERROR
>> TypeError: Cannot call method 'charAt' of null 0 [ 'TypeError: Cannot call method \'charAt\' of null' ]
>> In order for this task to work properly, PhantomJS must be installed locally
>> via NPM. If you're seeing this message, generally that means the NPM install
>> has failed. Please submit an issue providing as much detail as possible at:
>> https://github.com/gruntjs/grunt-lib-phantomjs/issues
Warning: PhantomJS not found. Use --force to continue.

Aborted due to warnings.
```

a) Fix phantomjs not found:

```
npm install grunt-mocha -D
```

But now, when running:

```
grunt test
```

I get:

```
>> Local Npm module "grunt-lib-phantomjs" not found. Is it installed?
```

I've also tried to update grunt-lib-phantomjs and phantomjs to latest versions, and the install grunt-mocha didn't work any longer.

So I had to npm install phantomjs@1.9.0-1 --save-dev
but then again, 'Local Npm module "grunt-lib-phantomjs" not found. Is it installed?'

**Comment by Siddharth77** [comment]
Please do try below command where you have installed your grunt or from where you are running your grunt . It worked for me.

npm install --unsafe-perm
