### ISSUE TITLE
Upgrade to Phantom2

### ISSUE THREAD

**Issue by naugtur** [gruntjs/grunt-lib-phantomjs#74]
Are you considering an upgrade? 
How important is it for you?

**Comment by brodrigu** [comment]
:+1:

**Comment by dwelle** [comment]
+1

**Comment by lukeapage** [comment]
given the regressions (http://phantomjs.org/release-2.0.html), it would make sense to wait for a 2.1 (or 2.0.1) release with those issues fixed...

**Comment by moriakaice** [comment]
Two months later, has anything changed in the topic?

**Comment by fishermand46** [comment]
:+1: A [huge issue](https://github.com/ariya/phantomjs/issues/10522) was fixed in Phantom 2.0. Would be nice to see it upgraded here.

**Comment by nathancahill** [comment]
Also interested in upgrading to Phantom 2.0 :+1:

**Comment by mzgol** [comment]
package.json still [depends on Phantom older than 2](https://github.com/gruntjs/grunt-lib-phantomjs/blob/9452e07323b81c24f74be66cbf5caafff77d56fa/package.json#L19), seems that this bug shouldn't be closed yet?

**Comment by nathancahill** [comment]
There's a summary of reasons to hold off on 2.0 for now: travis-ci/travis-ci/issues/3225

At some point, 2.0.1 will be released (ariya/phantomjs/issues/12902) which should fix a number of regressions. Regardless, CoffeeScript is no longer supported, so switching to PhantomJS 2.0.x should be a major version increment.

Any thoughts on supporting both versions?

**Comment by antivanov** [comment]
If you want to use 2.0 you can try using the unofficial fork from 0.7.1 https://www.npmjs.com/package/grunt-lib-phantomjs2-unofficial, it works OK with grunt-contrib-jasmine

**Comment by Arkni** [comment]
@nathancahill 
phantomjs v2.1.1 was released and is available for download, see:
* https://twitter.com/AriyaHidayat/status/691492028383830017
