### ISSUE TITLE
Error when running v2.0.0 in Windows XP ( "phantomjs.exe is not  a valid Win32 application")

### ISSUE THREAD

**Issue by justa9** [gruntjs/grunt-lib-phantomjs#77]
I cannot seem to run phantomJS 2.0.0 under Windows XP. 
An error window "phantomjs.exe is not  a valid Win32 application" pops up and an "Access is denied." is being reported on the console (cmd.exe).

Version 1.9.7.0 (last installed) worked perfectly fine.

Any help?

**Comment by vladikoff** [comment]
> I cannot seem to run phantomJS 2.0.0 

https://github.com/ariya/phantomjs/issues

**Comment by justa9** [comment]
I am terribly sorry. Wrong window.
Apologies.
