### ISSUE TITLE
Error when using PhantomJS.spawn() with grunt.util.async.forEachSeries() after update to 0.7.0

### ISSUE THREAD

**Issue by SolomoN-ua** [gruntjs/grunt-lib-phantomjs#78]
Hi, maybe I'm doing something wrong, but after updating ```grunt-lib-phantomjs``` to version 0.7.0, I'm getting following error:
```
PhantomJS threw an error:ERROR
>> 0 [ '' ]
Warning: PhantomJS exited unexpectedly with exit code null. Use --force to continue.
```

I'm using PhantomJS.spawn() in grunt.util.async.forEachSeries() loop.
```js
grunt.util.async.forEachSeries(options.urls, function (url, next) {
    PhantomJS.spawn(host + url, {
        options: {
            phantomScript: phantomScript,
            timeout: options.timeout,
            cookies: options.cookies,
            page: options.page
        },
        done: function (error) {
            if (error) {
                done();
            } else {
                if (options.urls[options.urls.length - 1] === url.replace(host, '')) {
                    done();
                } else {
                    next();
                }
            }
        }
    });
});
```

Short debugging shows that issue was caused by this commit: 07bd6780b3f6a0d25fb2136c95ca6783bf739bcb

After changing this line ```phantomJSHandle.pid``` back to ```phantomJSHandle.connected``` everything works just as expected.

List of ```options.urls``` is huge, and process is failing each time in a different place.
Looks like PhantomJS is killed in the middle of processing list, and passing ```options.killTimeout``` with some big number (enough for processing the whole list) does not help.

**Comment by gr33nfury** [comment]
It looks like what happens is that the process is killed and then the cleanup function is ran again and trys to kill the process again. It does not appear to effect anything other than a false error thrown.
