### ISSUE TITLE
Use globally installed phantomjs

### ISSUE THREAD

**Issue by donny-dont** [gruntjs/grunt-lib-phantomjs#79]
We're using a CI service that is built on top of Docker images. To get the build time down, and in case the tar containing phantomjs is down, I was installing phantomjs in the container globally using `npm install -g phantomjs@1.9.16`. Whenever there's an `npm install` on the project it still goes and downloads phantomjs.

```
Looks like an `npm install -g`; unable to check for already installed version.
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
```

Is there any way around this behavior? I'm currently using grunt-contrib-qunit which depends on this library.

Thanks!

**Comment by Ky6uk** [comment]
Agree. I tried [solution](https://github.com/Medium/phantomjs#using-phantomjs-from-disk), but this is does not helped me. Local phantomjs available, global phantomjs too, binary defined in PATH, but receiving does again and again.

**Comment by Ky6uk** [comment]
@donny-dont also you can try my temporary solution — install phantomjs from local directory.

```json
{
  "devDependencies": {
    "phantomjs": "./assets/phantomjs"
  }
}
```

**Comment by mendirattanishant** [comment]
Anybody resolved this issue? I am facing same issue installing phamtomjs on circleci.

**Comment by mendirattanishant** [comment]
@donny-dont Please let me know if you found any solution to this problem.

**Comment by Arkni** [comment]
This is an issue with https://github.com/Medium/phantomjs as it is the package that install `PhantomJS` binaries. So please report the issue on their issue tracker.

Closing this for now, feel free to ask if you have followup questions.
