### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by mikewilcox** [gruntjs/grunt-lib-phantomjs#81]
I can't get my page to load. When the path is incorrect, I get a not found error, which tells me my path must be correct. 

When I launch the task, it just hangs. I added the timeout and it times out. I'm not sure what to do next.

**Comment by Arkni** [comment]
Have you fixed your problem ?
Which path are you talking about ?
Any suggestions about how we can fix that ? or what should be the error message then ?

**Comment by mikewilcox** [comment]
I can't remember what the problem was now. I think I used another tool.

**Comment by Arkni** [comment]
Ah, thanks for commenting.
I'll close this issue as `wontfix`, feel free to ask if you have followup questions.
