### ISSUE TITLE
issue with running jasmine with phantomjs 1.9.8.

### ISSUE THREAD

**Issue by udayas8451** [gruntjs/grunt-lib-phantomjs#86]
When in run jasmine using grunt i see the following message. But this generates specRunner html file.Im trying to get the test execution summary on command line. And it fails because of following message.

Running "jasmine:unit" (jasmine) task
Testing jasmine specs via PhantomJS

Warning: Cannot read property 'pid' of undefined Use --force to continue.

Aborted due to warnings.

Versions:
=======
Phantomjsjs: 1.9.8
grunt-contrib-jasmine: ~0.9(what ever is the latest)

"grunt server --stack" logs:
=====================
TypeError: Cannot read property 'pid' of undefined
    at kill (C:\nodejs\sample\node_modules\grunt-contrib-jasmine\node_modules\grun
t-lib-phantomjs\lib\phantomjs.js:59:28)
    at cleanup (C:\nodejs\sample\node_modules\grunt-contrib-jasmine\node_modules\g
runt-lib-phantomjs\lib\phantomjs.js:65:31)
    at C:\nodejs\sample\node_modules\grunt-contrib-jasmine\node_modules\grunt-lib-
phantomjs\lib\phantomjs.js:174:7
    at callDone (C:\nodejs\sample\node_modules\grunt\node_modules\grunt-legacy-uti
l\index.js:159:5)
    at Object.util.spawn (C:\nodejs\sample\node_modules\grunt\node_modules\grunt-l
egacy-util\index.js:178:7)
    at EventEmitter.exports.spawn (C:\nodejs\sample\node_modules\grunt-contrib-jas
mine\node_modules\grunt-lib-phantomjs\lib\phantomjs.js:164:41)
    at phantomRunner (C:\nodejs\sample\node_modules\grunt-contrib-jasmine\tasks\ja
smine.js:140:15)
    at Object.<anonymous> (C:\nodejs\sample\node_modules\grunt-contrib-jasmine\tas
ks\jasmine.js:108:5)
    at Object.<anonymous> (C:\nodejs\sample\node_modules\grunt\lib\grunt\task.js:2
64:15)
    at Object.thisTask.fn (C:\nodejs\sample\node_modules\grunt\lib\grunt\task.js:8
2:16)

Aborted due to warnings.

I know the latest phantomjs is 2.0.0. but this does not really help. I want to see the lopgs on command line. Is there a module that does this?

Please help me. What am I doing wrong here?

Thanks!

**Comment by laurahk** [comment]
I have the same issue. If I remove the grunt-contrib-jasmine and npm install it works, until I swap branches and it breaks again.

**Comment by starstuffharvestingstarlight** [comment]
Got the same error, reinstalled ``grunt-contrib-jasmine`` forcing a new download of PhantomJS and that fixed it. Will let you guys know if it shows up again.

### Versions
```
npm 3.3.9
node 0.12.7
grunt-contrib-jasmine@0.9.2
grunt-lib-phantomjs@0.7.1
```

### Trace
```
Testing jasmine specs via PhantomJS

Warning: Cannot read property 'pid' of undefined Use --force to continue.
TypeError: Cannot read property 'pid' of undefined
    at kill (/.../node_modules/grunt-lib-phantomjs/lib/phantomjs.js:59:28)
    at cleanup (/.../node_modules/grunt-lib-phantomjs/lib/phantomjs.js:65:31)
    at /.../node_modules/grunt-lib-phantomjs/lib/phantomjs.js:174:7
    at callDone (/.../node_modules/grunt/node_modules/grunt-legacy-util/index.js:159:5)
    at Object.util.spawn (/.../node_modules/grunt/node_modules/grunt-legacy-util/index.js:178:7)
    at EventEmitter.exports.spawn (/.../node_modules/grunt-lib-phantomjs/lib/phantomjs.js:164:41)
    at phantomRunner (/.../node_modules/grunt-contrib-jasmine/tasks/jasmine.js:140:15)
    at Object.<anonymous> (/.../node_modules/grunt-contrib-jasmine/tasks/jasmine.js:108:5)
    at Object.<anonymous> (/.../node_modules/grunt/lib/grunt/task.js:264:15)
    at Object.thisTask.fn (/.../node_modules/grunt/lib/grunt/task.js:82:16)
```

**Comment by nathancahill** [comment]
@laurahk, you should have [node_modules in your .gitignore file](https://docs.npmjs.com/misc/faq#should-i-check-my-node-modules-folder-into-git). Here's a good starting place for node: https://github.com/github/gitignore/blob/master/Node.gitignore.

That'll fix your branching problem.

**Comment by laurahk** [comment]
@nathancahill it is in .gitignore. Not sure what was causing it, but after upgrading OS and re-cloning everything, it's been working fine. Must have had some conflicting config somewhere. Thanks anyway.

**Comment by ejosafat** [comment]
I got the same issue. I run tests in different parts of the app using both karma and grunt-contrib-jasmine.

For the first one I have to explicitly set in my package.json the dependency with phantomjs-prebuilt 2.1.4, otherwise karma fails as npm 3 doesn't install it, but does make grunt-lib-phantomjs fails, as despite of specifying in your repo the the new package name, phantomjs-prebuilt, it seems that the published version in the npm registry still use the old one, phantomjs, so no specifying the prebuilt version fix the problem.

In my case, this makes karma fails as it looks for the prebuilt version, so in the end I have to specify both to make everything work together.

I don't have much knowledge about npm, but maybe a version number bump + publish again will fix this?

**Comment by Arkni** [comment]
@ejosafat 

> For the first one I have to explicitly set in my package.json the dependency with phantomjs-prebuilt 2.1.4, otherwise karma fails as npm 3 doesn't install it

the package `phantomjs` is just deprecated, but that doesn't mean `npm@3` can't install it.

> In my case, this makes karma fails as it looks for the prebuilt version, so in the end I have to specify both to make everything work together.

`Karma` doesn't depend on `phantomjs` nor `phantomjs-prebuilt`. In their package.json, `phantomjs-prebuilt` is a `devDependency`. Also, you said you're using `grunt-contrib-jasmine` which depend on this package, which in its turn depend on the deprecated `phantomjs` package.
So, can you please explain what you mean by `this makes karma fails as it looks for the prebuilt version` ?
Are you using `karma-phantomjs-launcher` ? if yes, please report the issue there as they still use `peerDependencies` [1] which not be installed using `npm@3` ?

[1]:
>We will also be changing the behavior of peerDependencies in npm@3. We won’t be automatically downloading the peer dependency anymore. Instead, we’ll warn you if the peer dependency isn’t already installed. This requires you to resolve peerDependency conflicts yourself, manually, but in the long run this should make it less likely that you’ll end up in a tricky spot with your packages’ dependencies. - http://blog.npmjs.org/post/110924823920/npm-weekly-5

**Comment by ejosafat** [comment]
yes, sorry, I explained myself so badly! Thanks for the quick answer and clarifying it for me! It's a peerDependency as you say, that's why npm@3 doesn't install it and I have explicitly  to add it to the package.json, but doing that makes this plugin fails as in the published version it still looks for the phantomjs one. 

Any chance of getting published the current version which lists the phantomjs-prebuilt as a dependency instead of phantomjs?

**Comment by Arkni** [comment]
As I said in my previous comment, please report the issue about `peerDependencies` to `karma-phantomjs-launcher`'s repo. This way you can make sure that `phantomjs-prebuild` will be installed whether you're also using `grunt-contrib-jasmine` or not.

>Any chance of getting published the current version which lists the phantomjs-prebuilt as a dependency instead of phantomjs?

We will see if we can publish a new version this weekend or the next week maybe.

**Comment by Arkni** [comment]
@ejosafat 
FYI `v1.0.1` has been released, so your problem should be solved now.

---

AFAICT, this issue is related to the installation of `PhantomJS` binaries which should be reported in https://github.com/Medium/phantomjs.

Closing this for now, feel free to ask if you have followup questions.

**Comment by ejosafat** [comment]
great, thanks!
