### ISSUE TITLE
Getting ERROR >> 0 [ '' ] when running grunt jasmine

### ISSUE THREAD

**Issue by franksama** [gruntjs/grunt-lib-phantomjs#89]
Hi,

I'm trying to run the example app mentioned in the README and am getting the following error.  Anyone know a solution for it?

Thanks~!

```
Running "jasmine:src" (jasmine) task
Testing jasmine specs via phantom

Running PhantomJS...ERROR
>> 0 [ '' ]
Warning: PhantomJS exited unexpectedly with exit code null. Use --force to continue.

Aborted due to warnings.
```

**Comment by rovolution** [comment]
@franksama i am also getting this error as well. How did you go about resolving this? Thanks!

**Comment by jstncno** [comment]
+1

**Comment by franksama** [comment]
@rovolution - hmm i think to get this working i did

```
cd node_modules/grunt-contrib-jasmine/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/phantom
upx -d bin/phantomjs
```

**Comment by jstncno** [comment]
thanks @franksama ! will try

**Comment by rovolution** [comment]
@franksama That worked! Thanks! But still I wonder why you have to manually unpack the phantom binary with `upx`
