### ISSUE TITLE
Missing tag for the latest version

### ISSUE THREAD

**Issue by pomek** [gruntjs/grunt-lib-phantomjs#99]
Hi,

Everything looks pretty awesome, but I have one small question - why the latest version hasn't released any tag?

Package [`grunt-contrib-jasmine`](https://github.com/gruntjs/grunt-contrib-jasmine) by default using [`grunt-lib-phantomjs`](https://github.com/gruntjs/grunt-lib-phantomjs/blob/v1.0.0) released with tag `1.0.0`, but this version contains invalid [dependencies](https://github.com/gruntjs/grunt-lib-phantomjs/blob/v1.0.0/package.json#L19) (`phantomjs => phantomjs-prebuilt`).

Probably, I shall override (somehow) dependencies in my `package.json`, but why do I have to do the same thing every time?

**Comment by mgol** [comment]
This is not an *invalid* dependency; the `phantomjs` package will stay there forever, it's just deprecated. There are no new features & bug fixes because of the package name change so until there is something there's no point in releasing an update.

**Comment by pomek** [comment]
Tell me please, how I can install package [`grunt-contrib-jasmine`](https://github.com/gruntjs/grunt-contrib-jasmine), which based on [`grunt-lib-phantomjs`](https://github.com/gruntjs/grunt-lib-phantomjs/blob/v1.0.0), which based on PhantomJS, which not working.

I really don't understand thought:

> package will stay there forever, it's just deprecated

Something doesn't work, but it has to stay here, because… Why? 
Whatever you will do, Grunt Jasmine doesn't work through not working Grunt Phantom, so if I would like to fix Jasmine, firstly I have to fix Phantom. I just want a new tag for the latest changes from `master` branch.

**Comment by mgol** [comment]
Why do you think the `phantomjs` package name is causing your problem? This seems completely unrelated.

**Comment by pomek** [comment]
I have similar errors like: https://github.com/gruntjs/grunt-lib-phantomjs/issues/86 and https://github.com/gruntjs/grunt-lib-phantomjs/issues/79. It began to work when I replaced the `phantomjs` package to `phantomjs-prebuilt`.

**Comment by mgol** [comment]
Is there still sn error if you remove node_modules & run "npm install"
again? Did you switch to the phantomjs-prebuilt package in the same version
as phantomjs or fid you change the version as well?

On Wednesday, 3 February 2016, Kamil Piechaczek <notifications@github.com>
wrote:

> I have similar errors like: #86
> <https://github.com/gruntjs/grunt-lib-phantomjs/issues/86> and #79
> <https://github.com/gruntjs/grunt-lib-phantomjs/issues/79>. It began to
> work when I replaced the phantomjs package to phantomjs-prebuilt.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gruntjs/grunt-lib-phantomjs/issues/99#issuecomment-179178961>
> .
>


-- 
Michał Gołębiowski

**Comment by pomek** [comment]
Unfortunately, it doesn't help :(

**Comment by Arkni** [comment]
@pomek 
There are lot of other packages which depend on this package, and no one report any issue.
Can you please be specific and tell us what's not working for you ?

**Comment by pomek** [comment]
Hmm… I would like to prepare for us step list, but it began to work. I don't understand what I did wrong. 

I reinstalled npm modules two times and everything works fine.

Sorry for the trouble.
